---

- name: DMZ Server
  hosts: "{{ hosts }}"

  pre_tasks:
    - name: Update apt
      become: yes
      apt:
        update_cache: yes

  roles:
    - role: ansible-city.swap
      swap:
        blocks_count: 1024
        sysctl:
          - name: vm.swappiness
            value: 90

    - role: ansible-city.users_and_groups
      users_and_groups:
        users_folder: "{{ pwd }}/ansible/files/users_and_groups/users"
        groups:
          - name: admin
        users:
          - name: maciek.oledzki
            ssh_key: "{{ pwd }}/ansible/files/users_and_groups/users/maciek.oledzki/id_rsa.pub"
            groups:
              - admin
          - name: wojtek.oledzki
            ssh_key: "{{ pwd }}/ansible/files/users_and_groups/users/wojtek.oledzki/id_rsa.pub"
            groups:
              - admin
        sudoers:
          - name: admin
            user: "%admin"
            runas: "ALL=(ALL)"
            commands: "NOPASSWD: ALL"
