---

- name: Base
  include: "{{ pwd }}/ansible/playbook/base.yml"

- name: DMZ Server
  hosts: "{{ hosts }}"

  pre_tasks:
    - name: Update apt
      become: yes
      apt:
        update_cache: yes

  roles:
    - role: ansible-city.swap
      swap:
        blocks_count: 1024
        sysctl:
          - name: vm.swappiness
            value: 90
