---

- name: Base
  include: "{{ pwd }}/ansible/playbook/base.yml"

- name: Go CD Agents
  hosts: "{{ hosts }}"

  pre_tasks:
    - name: Update apt
      become: yes
      apt:
        update_cache: yes

  roles:
    - role: ansible-city.swap
      swap:
        blocks_count: 2048
        sysctl:
          - name: vm.swappiness
            value: 90

    - role: ansible-city.gocd_agent
      gocd_agent:
        server: 192.168.1.37
